version: '3'
volumes:
   data:
networks:
  local-keycloak:
services:
  postgres:
    image: postgres/postgres:12-alpine
    env_file:
      - .env
    hostname: keycloak
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - local-keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    env_file:
      - .env
    container_name: local_keycloak
    hostname: ${HOST}
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    command: 
      - 'start'
      - '--auto-build'
      - '--db=postgres'
      - '--hostname=${HOST}'
      - '--https-certificate-file=/certs/cert.pem'
      - '--https-certificate-key-file=/certs/key.pem' 
      - '--db-url-host=postgres'
      - '--db-username=${POSTGRESQL_USER}'
      - '--db-password=${POSTGRESQL_PASS}'
    volumes: 
      - ./certs:/certs
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - local-keycloak
    depends_on:
      - postgres